remote_theme: thelehhman/texture

# Build settings
theme: texture

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

texture:
  title: Viktor Çitaku
  tagline: Software Engineer
  date_format: "%b %-d, %Y"

  social_links:
    twitter: viktorcitaku
    github:  viktorcitaku
    linkedIn: in/viktor-çitaku-234a9b60/ # format: locale/username

  style: [black] # [yellow|red|black|blue|green|purple]
  showPicker: false # show the texture selector(development purposes)
  show_excerpts: true
  showNav: true
  analytics_id: UA-119580132-1